### ISSUE TITLE
Question: Getting NDEF message data in callback

### ISSUE THREAD

**Issue by chrisbradleyrun** [krish-dev/cordova-plugin-k-nfc-acr122u#1]
Hi @krish-dev  - Many thanks for creating this library.

I've got it working successfully but would like to get access the NDEF message stored on the tag too.

Do you know if it's possible to do this?

**Comment by krish-dev** [comment]
As of now this plugin only returns tag `uid`. for NDEF it's required to do some additional code.

**Comment by markus-fischbacher** [comment]
I want to use it in my Ionic app. Getting following error when building release:

```
[22:07:08]  typescript error 
            Can't resolve all parameters for NfcServiceProvider in 
            C:/dev/git/src/providers/nfc-service/nfc-service.ts: ([object Object], ?, [object
            Object], [object Object], [object Object]).

[22:07:08]  ionic-app-script task: "build" 
[22:07:08]  Error: The Angular AoT build failed. See the issues above 
Error: The Angular AoT build failed. See the issues above
    at C:\dev\git\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:237:55
    at step (C:\dev\git\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:32:23)
    at Object.next (C:\dev\git\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:13:53)
    at fulfilled (C:\dev\git\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:4:58)
[ERROR] An error occurred while running subprocess ionic-app-scripts.

        ionic-app-scripts build --prod --target cordova --platform android exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
Ionic build failed
```

Ionic is not able to resolve the type KNfcAcr122U

Any idea what to do?
